### ISSUE TITLE
Return the full date+time instead of only the hour

### ISSUE THREAD

**Issue by LudovicRousseau** [Pirionfr/pyLinky#10]
Only the hour+minute is returned in a format like:
```
[
  {
    "time": "00:00",
    "conso": 0.202
  },
  {
    "time": "00:30",
    "conso": 0.174
  },
  {
    "time": "01:00",
    "conso": 0.172
  },
...
]

```
This is problematic if I want to the data for another day. A more useful format would be to use the `dateDebut` field to return a full date + time.

Do you plan to modify/improve pyLinky or should I just work directly on the improved fork https://github.com/empierre/domoticz_linky?

**Comment by Pirionfr** [comment]
maybe I'm wrong but I think you can't get hourly data from an other day than day -1

**Comment by LudovicRousseau** [comment]
AFAIK you can get hourly data for any day. That is how I fetched the old data to fill my influxdb database.

**Comment by Pirionfr** [comment]
ok so we can add a paramter in init with the formatting wanted  and add fetch_data(self, date) to handle all date

**Comment by LudovicRousseau** [comment]
Problem fixed in my fork https://github.com/LudovicRousseau/pyLinky
