### ISSUE TITLE
Retrieve hourly data for "any day"

### ISSUE THREAD

**Issue by barasher** [Pirionfr/pyLinky#23]
I already use pyLinky to retrieve everyday my hourly consumption for the last day and store it in an InfluxDB database (https://github.com/barasher/linky-to-influxdb).

I'd like now to retrieve all the hourly data available "in the past".

The current workflow to retrieve day by day data is the following :
- `fetch_data` is called, it gets "raw" yearly, monthly, daily and hourly data calling `get_data_per_period` and store each result in `_data` dictionary
- then `get_data` is finally called to format data

When I want to retrieve my hourly data for the 1st of January 2019 for instance, I have to:
- call `get_data_per_period` with proper parameters
- **store retrieved data in `_data`**
- call `get_data` to retrieve properly formatted data

I think that it would be more logical to directly fill `_data` dictionary within the `get_data_per_period` method.

This way, you would have methods to retrieve 
- the yearly, monthly, daily and hourly data based on the day before the current day
- the yearly monthly, daily or hourly data for any period
- **with a unique, unified model (JSON)**

Would you be interested in such a patch ? I can do it and provide you a PR. I'd just would like if it's worth the pain :p

**Comment by barasher** [comment]
To go further, I think at the end that there are three general use-cases:
- get me **formatted** data concerning **yesterday**'s daily, monthly, yearly and hourly consumption (what the main do)
- get me **raw** data for a period (single date range plus granularity)
- get me **formated** data for a period (single date range plus granularity)

It would be interresting to share a common json template for the 2 **formated data** use-cases and another one for the **raw** use-case.

It should be possible to implement without breaking backward compatibility

**Comment by Pirionfr** [comment]
there is other person that will be interested by such feature ?

**Comment by barasher** [comment]
Let's just consider my initial post.

I think that if a client is interrested in retrieving your current consumption, then he will probably also be interrested in his "history". And with the current library, it's quite tricky to retrieve..

At the end, it really depends on the use-cases that you want to cover with Pylinky:
- If you just want to allow your library to retrieve "current" data, then this version is OK, functionnaly speaking.
- If you want your library to be used to retrieve data "in the past", then having to manually fill the `_data` dictionary is really non-intuitive in a client point of vue.

I'll send you a merge request for my intial post, it will perhaps be easier to discuss about it.
