### ISSUE TITLE
Update on Pypi

### ISSUE THREAD

**Issue by Debaru** [Pirionfr/pyLinky#6]
Hello,

If you've some time, can you update pyLinky on Pypi ? I'm waiting last version to fix a bug on Home Assistant Pylinky module :)

Thank you.

**Comment by Pirionfr** [comment]
I will do it today

Le jeu. 18 oct. 2018 à 18:17, Julien Debaru <notifications@github.com> a
écrit :

**Comment by Debaru** [comment]
Thanks :)

**Comment by Pirionfr** [comment]
Done

**Comment by Debaru** [comment]
I've tried to install with pip (` pip install pylinky==0.1.7`), but it doesn't work :

> Could not find a version that satisfies the requirement pylinky==0.1.7

Do you have same issue ?

**Comment by Pirionfr** [comment]
Python version maybe ?

**Comment by Debaru** [comment]
I don't think so. I'm still using same version (Python 3.5).
You don't have same issue ? 
On [https://pypi.org/simple/pylinky/](https://pypi.org/simple/pylinky/), for 0.1.7 version, i don't see .tar file, and pip doesn't support .egg file. Any chance that issue come from there?

**Comment by Pirionfr** [comment]
yes I have the same issue 

> Could not find a version that satisfies the requirement pylinky==0.1.7 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6)
No matching distribution found for pylinky==0.1.7

**Comment by Debaru** [comment]
Did you [generate distribution archive ](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives)?

**Comment by Debaru** [comment]
Last version (0.1.8) seem to fix issue problem for me.
