### ISSUE TITLE
Why not export get_data_per_hour() and others?

### ISSUE THREAD

**Issue by LudovicRousseau** [Pirionfr/pyLinky#9]
The class `LinkyClient()` defines a method `_get_data_per_hour(self, start_date, end_date)`.
https://github.com/Pirionfr/pyLinky/blob/master/pylinky/client.py#L103

Why not rename it without the leading '`_`' so that it is no more considered as internal only?
This would be useful and could prevent forks like domoticz_linky to diverge from pyLinky to provide such a method.
https://github.com/empierre/domoticz_linky/blob/master/linky.py#L80

It would be better if domoticz_linky could just use pyLinky module as-is.

**Comment by Pirionfr** [comment]
if you need for domoticz you can do a pull request, and I will create a new version on pypi

**Comment by LudovicRousseau** [comment]
I would also need an equivalent of `export_hours_values_json_format()` and other methods
https://github.com/empierre/domoticz_linky/blob/master/linky_json.py#L81

One major problem is that your code is licensed under Apache v2.0 and domoticz_linky uses GNU GPL v3. Maybe you don't want to include GNU GPL v3 code and move the whole project to this licence?

**Comment by Pirionfr** [comment]
I think we can dev an json export.
what format you need ?

**Comment by LudovicRousseau** [comment]
Do you plan to move from Apache 2.0 to GNU GPL v3?

**Comment by LudovicRousseau** [comment]
Problem fixed in my fork https://github.com/LudovicRousseau/pyLinky

I do not propose a Pull Request because I changed the licence to reuse GNU GPL code from https://github.com/empierre/domoticz_linky
If you change the licence I will create a PR so you can merge my changes.

**Comment by seblucas** [comment]
+1 for a merge

For the licence, I guess as this lib is inspired by a GPLv3 lib, staying with GPLv3 make sense

**Comment by Pirionfr** [comment]
go head make the pull request

**Comment by LudovicRousseau** [comment]
PR available
https://github.com/Pirionfr/pyLinky/pull/13

**Comment by grea09** [comment]
We actually exported a function to get any interval of time at any scale. Maybe this answers this issue ?

**Comment by LudovicRousseau** [comment]
New PR proposed in https://github.com/Pirionfr/pyLinky/pull/18

**Comment by Pirionfr** [comment]
merge available in v0.3.0
